name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Lấy source code từ GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2) Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3) Build project
      - name: Build Project
        run: dotnet build --configuration Release

      # 4) Run Unit Tests (nếu bạn chưa có test thì dòng này vẫn chạy OK)
      - name: Run Tests
        run: dotnet test --no-build

      # 5) Build Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/urlshortener:${{ github.sha }} .

      # 6) Login Docker Hub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      # 7) Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/urlshortener:${{ github.sha }}

      # 8) Deploy to Render via Webhook
      - name: Deploy to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
